language: scala
scala:
  - 2.11.8
sudo: false
jdk:
- oraclejdk8
#after_success:
#- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

